typography_spectrum: 0.5220646683592349
color:
  brandStrength: 0.8224947932176292
  lightness: 0.719587137689814
  saturation: 0.14504283014684916
  rhythmicContrast: 0.1752328926231712
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
opengraph:
  type: ''
layout_spectrum: 0.01748779439367354
author:
  name: Marco and Mauro La Villa
  email: info@easterncanal.com
  url: marcoandmaurolavilla.com
name: marcoandmaurolavilla
navigation:
  - name: About
    url: marcoandmaurolavilla.com
    type: external
title: Hello
